version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: wedding-db
    environment:
      POSTGRES_USER: YOUR_DB_USERNAME
      POSTGRES_PASSWORD: YOUR_DB_PASSWORD
      POSTGRES_DB: weddingdb
    ports:
      - "5432:5432"
    volumes:
      - wedding-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U YOUR_DB_USERNAME" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: wedding-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: YOUR_EMAIL
      PGADMIN_DEFAULT_PASSWORD: YOUR_PGADMIN_PASSWORD
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  wedding-postgres-data:
  pgadmin-data:
